#include "Plans/Tests/TestsAlex/constraints/TestCommunicationMaster1528124971225Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1528124971225) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestCommunicationMaster

/*		
 * Tasks: 
 * - EP:1528124971227 : DefaultTask (1414681164704)
 *
 * States:
 * - TestStop (1528124971226)
 * - TestSart (1528125127758)
 *
 * Vars:
 */

// State: TestStop

// State: TestStop

// State: TestSart

// State: TestSart

}
