#include "Plans/Tests/TestsAlex/TestCommunicationMaster1528124971225.h"
using namespace alica;
/*PROTECTED REGION ID(eph1528124971225) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TestCommunicationMaster

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1528124971227

     */
    shared_ptr<UtilityFunction> UtilityFunction1528124971225::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1528124971225) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: TestStop in Plan: TestCommunicationMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Start signal received 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1528124971227)
     *
     * States:
     *   - TestStop (1528124971226)
     *   - TestSart (1528125127758)
     *
     * Vars:
     */
    bool TransitionCondition1528125190720::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1528125189377) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: TestSart in Plan: TestCommunicationMaster

}
