#ifndef ASPFindFreeDockingStationMasterCONSTRAINT_H_
#define ASPFindFreeDockingStationMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

    class Constraint1470042926317 : public BasicConstraint
    {
        void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
    };

} /* namespace alica */

#endif /* ASPFindFreeDockingStationMasterCONSTRAINT_H_ */
