#ifndef ASPNavwoExternalsInnerCONSTRAINT_H_
#define ASPNavwoExternalsInner_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

    class Constraint1477229712321 : public BasicConstraint
    {
        void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
    };

} /* namespace alica */

#endif /* ASPNavwoExternalsInnerCONSTRAINT_H_ */
