#pragma once

#include <engine/BasicConstraint.h>
#include <iostream>
#include <memory>

using std::exception;
using std::make_shared;
using std::shared_ptr;
using std::cout;
using namespace alica;

namespace alica
{
class ProblemDescriptor;
class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */
