#include "Plans/Serve/constraints/ASPNavwoExternals1477229620130Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1477229620130) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:ASPNavwoExternals

    /*		
     * Tasks: 
     * - EP:1477229620132 : DefaultTask (1414681164704)
     *
     * States:
     * - Nav1 (1477229620131)
     * - InnerState (1477229628161)
     * - NewSuccessState (1477229672639)
     *
     * Vars:				
     * - PlanVar1 (1477229962547) 
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: [PlanVar1]
     * Domain Variables:

     */
    void Constraint1477229706852::getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1477229706852) ENABLED START*/
        /*PROTECTED REGION END*/
    }

// State: Nav1

// State: Nav1

// State: InnerState

// State: InnerState

// State: NewSuccessState

// State: NewSuccessState

}
