#include "Plans/Serve/constraints/ASPNavigateMaster1475692538365Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1475692538365) ENABLED START*/
//Add additional using directives here
#include <alica_asp_solver/ASPTerm.h>
#include <alica_asp_solver/ASPSolver.h>
#include <alica_asp_solver/ASPQueryType.h>
#include <SolverType.h>
#include <engine/AlicaEngine.h>
#include "engine/constraintmodul/SolverTerm.h"
#include <engine/constraintmodul/ProblemDescriptor.h>
#include <memory>
#include "TTBWorldModel.h"
#include "Doors.h"
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:ASPNavigateMaster

    /*		
     * Tasks: 
     * - EP:1475692538367 : DefaultTask (1414681164704)
     *
     * States:
     * - Navigate (1475692538366)
     * - Stop (1476366084811)
     *
     * Vars:				
     * - NavMasterVar (1475698052801) 
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: [NavMasterVar]
     * Domain Variables:

     */
    void Constraint1475692986360::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1475692986360) ENABLED START*/
        ttb::TTBWorldModel* wm = ttb::TTBWorldModel::get();
        auto constraint = make_shared<alica::reasoner::ASPTerm>();
        //The query id has to be added to any predicate which is added to the program, naming ruleheads and facts!
        auto queryId = ((alica::reasoner::ASPSolver*)wm->getEngine()->getSolver(SolverType::ASPSOLVER))->getQueryCounter();
        constraint->setQueryId(queryId);
        stringstream ss;
        ss << "goalReachable(X, " << queryId << ") :- reachable(X, Y), goal(X, ";
        ss << queryId << "), start(Y, "  << queryId << "), room(X), room(Y).";
        constraint->setRule(ss.str());
        ss.str("");
        ss << "goal(r1405B, " << queryId << ").";
        constraint->addFact(ss.str());
        ss.str("");
        ss << "start(r1411, " << queryId << ").";
        constraint->addFact(ss.str());
        constraint->setProgramSection("distributedSystemsRoomsExternal");
        constraint->setType(alica::reasoner::ASPQueryType::Variable);
        constraint->setId(1475692986360);
        constraint->setExternals(wm->doors.getDoors());
        c->setConstraint(dynamic_pointer_cast < alica::SolverTerm > (constraint));
        /*PROTECTED REGION END*/
    }

// State: Navigate

// State: Navigate

// State: Stop

// State: Stop

}
