#include "Plans/Serve/constraints/CarryBookMaster1468493942500Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1468493942500) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CarryBookMaster

/*		
 * Tasks: 
 * - EP:1468493942503 : CleanUp (1414682595019)
 * - EP:1468494400454 : Fetch (1468494562045)
 * - EP:1468494403537 : DefaultTask (1414681164704)
 *
 * States:
 * - CarryBookState1 (1468493942502)
 * - CarryBookState2 (1468493959103)
 * - TestState (1468493961311)
 *
 * Vars:
 */

// State: CarryBookState1

// State: CarryBookState1

// State: CarryBookState2

// State: CarryBookState2

// State: TestState

// State: TestState

}
