#include "Plans/Serve/constraints/Charge1454331030770Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1454331030770) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Charge

/*		
 * Tasks: 
 * - EP:1454331045285 : DefaultTask (1414681164704)
 *
 * States:
 * - SearchDock (1454331097632)
 * - ChargeAccu (1454331108755)
 * - FullyCharged (1454331131268)
 *
 * Vars:
 */

// State: SearchDock

// State: SearchDock

// State: ChargeAccu

// State: ChargeAccu

// State: FullyCharged

// State: FullyCharged

}
