#include "Plans/Serve/constraints/PutDown1520511951867Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1520511951867) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:PutDown

/*		
 * Tasks: 
 * - EP:1520511964768 : DefaultTask (1414681164704)
 *
 * States:
 * - NewState (1520511964767)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
