#include "Plans/Serve/constraints/Search1520437018620Constraints.h"
/*PROTECTED REGION ID(ch1520437018620) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

using std::exception;
using std::make_shared;
using std::cout;
using namespace alica;

namespace alicaAutogenerated
{
// Plan:Search
/*
* Tasks:
* - EP:1520437031578 : Search (1481544910904)
*
* States:
* - DriveAround (1520437031577)
* - FoundEntity (1520438026668)
*
* Vars:
* - entity (1520437454401)
*/
/*
* RuntimeCondition - (Name): NewRuntimeCondition
* (ConditionString):
* Static Variables: entity
* Domain Variables:
*
*/
void Constraint1520437448508::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1520437448508) ENABLED START*/
    /*PROTECTED REGION END*/
}

// State: DriveAround
// State: FoundEntity
}
