#include "Plans/Serve/constraints/ServeMaster1454332108133Constraints.h"
/*PROTECTED REGION ID(ch1454332108133) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

using std::exception;
using std::make_shared;
using std::cout;
using namespace alica;

namespace alicaAutogenerated
{
// Plan:ServeMaster
/*
* Tasks:
* - EP:1454332108135 : DefaultTask (1414681164704)
*
* States:
* - Stop (1454332108134)
* - Serve (1454332119685)
* - Charge (1454332121310)
*
* Vars:
*/

// State: Stop
// State: Serve
// State: Charge
}
