#include "Plans/Serve/constraints/Serve1454331313621Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1454331313621) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Serve

/*		
 * Tasks: 
 * - EP:1454331321920 : DefaultTask (1414681164704)
 *
 * States:
 * - WaitForTask (1454331321919)
 * - DriveTo (1454331334336)
 * - SearchFor (1454331358257)
 * - PickUp (1486383776159)
 *
 * Vars:
 */

// State: WaitForTask

// State: WaitForTask

// State: DriveTo

// State: DriveTo

// State: SearchFor

// State: SearchFor

// State: PickUp

// State: PickUp

}
