#ifndef CollectBoxesCONSTRAINT_H_
#define CollectBoxes_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
class RunningPlan;
}

namespace alicaAutogenerated
{

} // namespace alicaAutogenerated

#endif /* CollectBoxesCONSTRAINT_H_ */
