#ifndef SearchBoxesCONSTRAINT_H_
#define SearchBoxes_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* SearchBoxesCONSTRAINT_H_ */
