classdef PathPlanner < robotics.ros.Message
    %PathPlanner MATLAB implementation of msl_msgs/PathPlanner
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_msgs/PathPlanner' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f9c296b223d8c327a885eff4a4aab895' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MslMsgsPoint2dInfoClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_msgs/Point2dInfo') % Dispatch to MATLAB class for message type msl_msgs/Point2dInfo
    end
    
    properties (Dependent)
        SenderId
        PathPoints
    end
    
    properties (Access = protected)
        Cache = struct('PathPoints', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'PathPoints', 'SenderId'} % List of non-constant message properties
        ROSPropertyList = {'pathPoints', 'senderId'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = PathPlanner(msg)
            %PathPlanner Construct the message object PathPlanner
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function senderid = get.SenderId(obj)
            %get.SenderId Get the value for property SenderId
            senderid = int32(obj.JavaMessage.getSenderId);
        end
        
        function set.SenderId(obj, senderid)
            %set.SenderId Set the value for property SenderId
            validateattributes(senderid, {'numeric'}, {'nonempty', 'scalar'}, 'PathPlanner', 'SenderId');
            
            obj.JavaMessage.setSenderId(senderid);
        end
        
        function pathpoints = get.PathPoints(obj)
            %get.PathPoints Get the value for property PathPoints
            if isempty(obj.Cache.PathPoints)
                javaArray = obj.JavaMessage.getPathPoints;
                array = obj.readJavaArray(javaArray, obj.MslMsgsPoint2dInfoClass);
                obj.Cache.PathPoints = feval(obj.MslMsgsPoint2dInfoClass, array);
            end
            pathpoints = obj.Cache.PathPoints;
        end
        
        function set.PathPoints(obj, pathpoints)
            %set.PathPoints Set the value for property PathPoints
            if ~isvector(pathpoints) && isempty(pathpoints)
                % Allow empty [] input
                pathpoints = feval([obj.MslMsgsPoint2dInfoClass '.empty'], 0, 1);
            end
            
            validateattributes(pathpoints, {obj.MslMsgsPoint2dInfoClass}, {'vector'}, 'PathPlanner', 'PathPoints');
            
            javaArray = obj.JavaMessage.getPathPoints;
            array = obj.writeJavaArray(pathpoints, javaArray, obj.MslMsgsPoint2dInfoClass);
            obj.JavaMessage.setPathPoints(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.PathPoints)
                obj.Cache.PathPoints = [];
                obj.Cache.PathPoints = obj.PathPoints;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.PathPoints = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SenderId = obj.SenderId;
            
            % Recursively copy compound properties
            cpObj.PathPoints = copy(obj.PathPoints);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SenderId = strObj.SenderId;
            PathPointsCell = arrayfun(@(x) feval([obj.MslMsgsPoint2dInfoClass '.loadobj'], x), strObj.PathPoints, 'UniformOutput', false);
            obj.PathPoints = vertcat(PathPointsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SenderId = obj.SenderId;
            strObj.PathPoints = arrayfun(@(x) saveobj(x), obj.PathPoints);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_msgs.PathPlanner.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_msgs.PathPlanner;
            obj.reload(strObj);
        end
    end
end
