classdef AMCLPoseWrapped < robotics.ros.Message
    %AMCLPoseWrapped MATLAB implementation of ttb_msgs/AMCLPoseWrapped
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ttb_msgs/AMCLPoseWrapped' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '57660e94fee37d1bdcaace3a31dcb137' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoseWithCovarianceStampedClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/PoseWithCovarianceStamped') % Dispatch to MATLAB class for message type geometry_msgs/PoseWithCovarianceStamped
    end
    
    properties (Dependent)
        ReceiverId
        Msg
    end
    
    properties (Access = protected)
        Cache = struct('Msg', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Msg', 'ReceiverId'} % List of non-constant message properties
        ROSPropertyList = {'msg', 'receiverId'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = AMCLPoseWrapped(msg)
            %AMCLPoseWrapped Construct the message object AMCLPoseWrapped
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function receiverid = get.ReceiverId(obj)
            %get.ReceiverId Get the value for property ReceiverId
            receiverid = int32(obj.JavaMessage.getReceiverId);
        end
        
        function set.ReceiverId(obj, receiverid)
            %set.ReceiverId Set the value for property ReceiverId
            validateattributes(receiverid, {'numeric'}, {'nonempty', 'scalar'}, 'AMCLPoseWrapped', 'ReceiverId');
            
            obj.JavaMessage.setReceiverId(receiverid);
        end
        
        function msg = get.Msg(obj)
            %get.Msg Get the value for property Msg
            if isempty(obj.Cache.Msg)
                obj.Cache.Msg = feval(obj.GeometryMsgsPoseWithCovarianceStampedClass, obj.JavaMessage.getMsg);
            end
            msg = obj.Cache.Msg;
        end
        
        function set.Msg(obj, msg)
            %set.Msg Set the value for property Msg
            validateattributes(msg, {obj.GeometryMsgsPoseWithCovarianceStampedClass}, {'nonempty', 'scalar'}, 'AMCLPoseWrapped', 'Msg');
            
            obj.JavaMessage.setMsg(msg.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Msg)
                obj.Cache.Msg.setJavaObject(msg.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Msg = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ReceiverId = obj.ReceiverId;
            
            % Recursively copy compound properties
            cpObj.Msg = copy(obj.Msg);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ReceiverId = strObj.ReceiverId;
            obj.Msg = feval([obj.GeometryMsgsPoseWithCovarianceStampedClass '.loadobj'], strObj.Msg);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ReceiverId = obj.ReceiverId;
            strObj.Msg = saveobj(obj.Msg);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ttb_msgs.AMCLPoseWrapped.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ttb_msgs.AMCLPoseWrapped;
            obj.reload(strObj);
        end
    end
end
