classdef ObjectSize < robotics.ros.Message
    %ObjectSize MATLAB implementation of ttb_msgs/ObjectSize
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ttb_msgs/ObjectSize' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd88a2aaf5eb6525af58a659aa9e5a83c' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Xlength
        Ylength
        Zlength
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Xlength', 'Ylength', 'Zlength'} % List of non-constant message properties
        ROSPropertyList = {'xlength', 'ylength', 'zlength'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ObjectSize(msg)
            %ObjectSize Construct the message object ObjectSize
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function xlength = get.Xlength(obj)
            %get.Xlength Get the value for property Xlength
            xlength = double(obj.JavaMessage.getXlength);
        end
        
        function set.Xlength(obj, xlength)
            %set.Xlength Set the value for property Xlength
            validateattributes(xlength, {'numeric'}, {'nonempty', 'scalar'}, 'ObjectSize', 'Xlength');
            
            obj.JavaMessage.setXlength(xlength);
        end
        
        function ylength = get.Ylength(obj)
            %get.Ylength Get the value for property Ylength
            ylength = double(obj.JavaMessage.getYlength);
        end
        
        function set.Ylength(obj, ylength)
            %set.Ylength Set the value for property Ylength
            validateattributes(ylength, {'numeric'}, {'nonempty', 'scalar'}, 'ObjectSize', 'Ylength');
            
            obj.JavaMessage.setYlength(ylength);
        end
        
        function zlength = get.Zlength(obj)
            %get.Zlength Get the value for property Zlength
            zlength = double(obj.JavaMessage.getZlength);
        end
        
        function set.Zlength(obj, zlength)
            %set.Zlength Set the value for property Zlength
            validateattributes(zlength, {'numeric'}, {'nonempty', 'scalar'}, 'ObjectSize', 'Zlength');
            
            obj.JavaMessage.setZlength(zlength);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Xlength = obj.Xlength;
            cpObj.Ylength = obj.Ylength;
            cpObj.Zlength = obj.Zlength;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Xlength = strObj.Xlength;
            obj.Ylength = strObj.Ylength;
            obj.Zlength = strObj.Zlength;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Xlength = obj.Xlength;
            strObj.Ylength = obj.Ylength;
            strObj.Zlength = obj.Zlength;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ttb_msgs.ObjectSize.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ttb_msgs.ObjectSize;
            obj.reload(strObj);
        end
    end
end
