#ifndef TestPOICONSTRAINT_H_
#define TestPOI_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TestPOICONSTRAINT_H_ */
