#include "Plans/Tests/TestDriveToPoi1517819007614.h"
using namespace alica;
/*PROTECTED REGION ID(eph1517819007614) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TestDriveToPoi

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1517819007616

     */
    shared_ptr<UtilityFunction> UtilityFunction1517819007614::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1517819007614) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: TestBeh in Plan: TestDriveToPoi

}
