#include "Plans/Wumpus/InteractWIthPlayground1489673751539.h"
using namespace alica;
/*PROTECTED REGION ID(eph1489673751539) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
	//Plan:InteractWIthPlayground

	/* generated comment

	 Task: DefaultTask  -> EntryPoint-ID: 1489673770247

	 */
	shared_ptr<UtilityFunction> UtilityFunction1489673751539::getUtilityFunction(Plan* plan)
	{
		/*PROTECTED REGION ID(1489673751539) ENABLED START*/

		shared_ptr<UtilityFunction> defaultFunction = make_shared<DefaultUtilityFunction>(plan);
		return defaultFunction;

		/*PROTECTED REGION END*/
	}

	//State: Wait in Plan: InteractWIthPlayground

	/*
	 *
	 * Transition:
	 *   - Name: MISSING_NAME, ConditionString: , Comment : Your turn
	 *
	 * Plans in State:
	 *   - Plan - (Name): WaitForTurnDefault, (PlanID): 1489673907866
	 *
	 * Tasks:
	 *   - DefaultTask (1414681164704) (Entrypoint: 1489673770247)
	 *
	 * States:
	 *   - Wait (1489673770246)
	 *   - Turn (1489673919099)
	 *
	 * Vars:
	 */
	bool TransitionCondition1489674024580::evaluate(shared_ptr<RunningPlan> rp)
	{
		/*PROTECTED REGION ID(1489674022732) ENABLED START*/
		auto actionResponse = wm->wumpusData.getActionResponse();
		if (actionResponse == nullptr)
		{
			return false;
		}
		if (actionResponse->agentId == this->wm->wumpusData.getOwnId())
		{
			//fix enums
			if (find(actionResponse->responses.begin(), actionResponse->responses.end(), 12)
					!= actionResponse->responses.end())
			{
//				cout << "OUR TURN" << endl;
				return true;
			}
		}
		return false;
		/*PROTECTED REGION END*/

	}

	//State: Turn in Plan: InteractWIthPlayground

	/*
	 *
	 * Transition:
	 *   - Name: MISSING_NAME, ConditionString: , Comment : Turn finished
	 *
	 * Plans in State:
	 *   - Plan - (Name): Turn, (PlanID): 1489674129255
	 *
	 * Tasks:
	 *   - DefaultTask (1414681164704) (Entrypoint: 1489673770247)
	 *
	 * States:
	 *   - Wait (1489673770246)
	 *   - Turn (1489673919099)
	 *
	 * Vars:
	 */
	bool TransitionCondition1489674025736::evaluate(shared_ptr<RunningPlan> rp)
	{
		/*PROTECTED REGION ID(1489674024781) ENABLED START*/
		auto ret = rp->anyChildrenStatus(PlanStatus::Success);
//		if (ret)
//		{
//			cout << "WAIT" << endl;
//		}
		return ret;
		/*PROTECTED REGION END*/

	}

}
