#include "Plans/Serve/PKVR16/constraints/SearchBoxes1481545038564Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1481545038564) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:SearchBoxes

/*		
 * Tasks: 
 * - EP:1481545053784 : DefaultTask (1414681164704)
 *
 * States:
 * - SearchBoxes (1481545053783)
 *
 * Vars:
 */

// State: SearchBoxes

// State: SearchBoxes

}
