#include "Plans/TurtleGenericTestMaster1414681057676.h"
using namespace alica;
/*PROTECTED REGION ID(eph1414681057676) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TurtleGenericTestMaster

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1414681057678

     */
    shared_ptr<UtilityFunction> UtilityFunction1414681057676::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1414681057676) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Stop in Plan: TurtleGenericTestMaster

    /*
     *		
     * Transition:
     *   - Name: Stop2DoSomething, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): StopDefault, (PlanID): 1414681278745 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1414681057678)
     *
     * States:
     *   - Stop (1414681057677)
     *   - DoSomething (1414681069778)
     *
     * Vars:
     */
    bool TransitionCondition1414681086048::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1414681083953) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: DoSomething in Plan: TurtleGenericTestMaster

    /*
     *		
     * Transition:
     *   - Name: DoSomething2Stop, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): SimpleDriveDefault, (PlanID): 1432735473356 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1414681057678)
     *
     * States:
     *   - Stop (1414681057677)
     *   - DoSomething (1414681069778)
     *
     * Vars:
     */
    bool TransitionCondition1414681505635::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1414681503803) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

}
