set(_CATKIN_CURRENT_PACKAGE "wumpus_simulator")
set(wumpus_simulator_VERSION "0.0.0")
set(wumpus_simulator_MAINTAINER "lab-user <lab-user@todo.todo>")
set(wumpus_simulator_PACKAGE_FORMAT "1")
set(wumpus_simulator_BUILD_DEPENDS "qtbase5-dev" "roscpp" "ttb_msgs" "system_config")
set(wumpus_simulator_BUILD_EXPORT_DEPENDS "rqt_gui" "ttb_msgs" "rqt_gui_cpp" "system_config" "libqt5-core" "libqt5-gui" "libqt5-widgets" "roscpp")
set(wumpus_simulator_BUILDTOOL_DEPENDS "catkin")
set(wumpus_simulator_BUILDTOOL_EXPORT_DEPENDS )
set(wumpus_simulator_EXEC_DEPENDS "rqt_gui" "ttb_msgs" "rqt_gui_cpp" "system_config" "libqt5-core" "libqt5-gui" "libqt5-widgets" "roscpp")
set(wumpus_simulator_RUN_DEPENDS "rqt_gui" "ttb_msgs" "rqt_gui_cpp" "system_config" "libqt5-core" "libqt5-gui" "libqt5-widgets" "roscpp")
set(wumpus_simulator_TEST_DEPENDS )
set(wumpus_simulator_DOC_DEPENDS )
set(wumpus_simulator_DEPRECATED "")