classdef CorrectedOdometryCovInfo < robotics.ros.Message
    %CorrectedOdometryCovInfo MATLAB implementation of msl_sensor_msgs/CorrectedOdometryCovInfo
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_sensor_msgs/CorrectedOdometryCovInfo' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4eb1ea3f94e7777012e75c47d796a4b8' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MslMsgsMotionInfoClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_msgs/MotionInfo') % Dispatch to MATLAB class for message type msl_msgs/MotionInfo
        MslMsgsPositionInfoClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_msgs/PositionInfo') % Dispatch to MATLAB class for message type msl_msgs/PositionInfo
        MslSensorMsgsCovMatrix3DClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_sensor_msgs/CovMatrix3D') % Dispatch to MATLAB class for message type msl_sensor_msgs/CovMatrix3D
        MslSensorMsgsLocalizationTypeClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_sensor_msgs/LocalizationType') % Dispatch to MATLAB class for message type msl_sensor_msgs/LocalizationType
    end
    
    properties (Dependent)
        Position
        Motion
        Timestamp
        Certainty
        LocType
        CovarianceMatrix
    end
    
    properties (Access = protected)
        Cache = struct('Position', [], 'Motion', [], 'LocType', [], 'CovarianceMatrix', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Certainty', 'CovarianceMatrix', 'LocType', 'Motion', 'Position', 'Timestamp'} % List of non-constant message properties
        ROSPropertyList = {'certainty', 'covarianceMatrix', 'locType', 'motion', 'position', 'timestamp'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = CorrectedOdometryCovInfo(msg)
            %CorrectedOdometryCovInfo Construct the message object CorrectedOdometryCovInfo
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function position = get.Position(obj)
            %get.Position Get the value for property Position
            if isempty(obj.Cache.Position)
                obj.Cache.Position = feval(obj.MslMsgsPositionInfoClass, obj.JavaMessage.getPosition);
            end
            position = obj.Cache.Position;
        end
        
        function set.Position(obj, position)
            %set.Position Set the value for property Position
            validateattributes(position, {obj.MslMsgsPositionInfoClass}, {'nonempty', 'scalar'}, 'CorrectedOdometryCovInfo', 'Position');
            
            obj.JavaMessage.setPosition(position.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Position)
                obj.Cache.Position.setJavaObject(position.getJavaObject);
            end
        end
        
        function motion = get.Motion(obj)
            %get.Motion Get the value for property Motion
            if isempty(obj.Cache.Motion)
                obj.Cache.Motion = feval(obj.MslMsgsMotionInfoClass, obj.JavaMessage.getMotion);
            end
            motion = obj.Cache.Motion;
        end
        
        function set.Motion(obj, motion)
            %set.Motion Set the value for property Motion
            validateattributes(motion, {obj.MslMsgsMotionInfoClass}, {'nonempty', 'scalar'}, 'CorrectedOdometryCovInfo', 'Motion');
            
            obj.JavaMessage.setMotion(motion.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Motion)
                obj.Cache.Motion.setJavaObject(motion.getJavaObject);
            end
        end
        
        function timestamp = get.Timestamp(obj)
            %get.Timestamp Get the value for property Timestamp
            timestamp = typecast(int64(obj.JavaMessage.getTimestamp), 'uint64');
        end
        
        function set.Timestamp(obj, timestamp)
            %set.Timestamp Set the value for property Timestamp
            validateattributes(timestamp, {'numeric'}, {'nonempty', 'scalar'}, 'CorrectedOdometryCovInfo', 'Timestamp');
            
            obj.JavaMessage.setTimestamp(timestamp);
        end
        
        function certainty = get.Certainty(obj)
            %get.Certainty Get the value for property Certainty
            certainty = double(obj.JavaMessage.getCertainty);
        end
        
        function set.Certainty(obj, certainty)
            %set.Certainty Set the value for property Certainty
            validateattributes(certainty, {'numeric'}, {'nonempty', 'scalar'}, 'CorrectedOdometryCovInfo', 'Certainty');
            
            obj.JavaMessage.setCertainty(certainty);
        end
        
        function loctype = get.LocType(obj)
            %get.LocType Get the value for property LocType
            if isempty(obj.Cache.LocType)
                obj.Cache.LocType = feval(obj.MslSensorMsgsLocalizationTypeClass, obj.JavaMessage.getLocType);
            end
            loctype = obj.Cache.LocType;
        end
        
        function set.LocType(obj, loctype)
            %set.LocType Set the value for property LocType
            validateattributes(loctype, {obj.MslSensorMsgsLocalizationTypeClass}, {'nonempty', 'scalar'}, 'CorrectedOdometryCovInfo', 'LocType');
            
            obj.JavaMessage.setLocType(loctype.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.LocType)
                obj.Cache.LocType.setJavaObject(loctype.getJavaObject);
            end
        end
        
        function covariancematrix = get.CovarianceMatrix(obj)
            %get.CovarianceMatrix Get the value for property CovarianceMatrix
            if isempty(obj.Cache.CovarianceMatrix)
                obj.Cache.CovarianceMatrix = feval(obj.MslSensorMsgsCovMatrix3DClass, obj.JavaMessage.getCovarianceMatrix);
            end
            covariancematrix = obj.Cache.CovarianceMatrix;
        end
        
        function set.CovarianceMatrix(obj, covariancematrix)
            %set.CovarianceMatrix Set the value for property CovarianceMatrix
            validateattributes(covariancematrix, {obj.MslSensorMsgsCovMatrix3DClass}, {'nonempty', 'scalar'}, 'CorrectedOdometryCovInfo', 'CovarianceMatrix');
            
            obj.JavaMessage.setCovarianceMatrix(covariancematrix.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.CovarianceMatrix)
                obj.Cache.CovarianceMatrix.setJavaObject(covariancematrix.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Position = [];
            obj.Cache.Motion = [];
            obj.Cache.LocType = [];
            obj.Cache.CovarianceMatrix = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Timestamp = obj.Timestamp;
            cpObj.Certainty = obj.Certainty;
            
            % Recursively copy compound properties
            cpObj.Position = copy(obj.Position);
            cpObj.Motion = copy(obj.Motion);
            cpObj.LocType = copy(obj.LocType);
            cpObj.CovarianceMatrix = copy(obj.CovarianceMatrix);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Timestamp = strObj.Timestamp;
            obj.Certainty = strObj.Certainty;
            obj.Position = feval([obj.MslMsgsPositionInfoClass '.loadobj'], strObj.Position);
            obj.Motion = feval([obj.MslMsgsMotionInfoClass '.loadobj'], strObj.Motion);
            obj.LocType = feval([obj.MslSensorMsgsLocalizationTypeClass '.loadobj'], strObj.LocType);
            obj.CovarianceMatrix = feval([obj.MslSensorMsgsCovMatrix3DClass '.loadobj'], strObj.CovarianceMatrix);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Timestamp = obj.Timestamp;
            strObj.Certainty = obj.Certainty;
            strObj.Position = saveobj(obj.Position);
            strObj.Motion = saveobj(obj.Motion);
            strObj.LocType = saveobj(obj.LocType);
            strObj.CovarianceMatrix = saveobj(obj.CovarianceMatrix);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_sensor_msgs.CorrectedOdometryCovInfo.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_sensor_msgs.CorrectedOdometryCovInfo;
            obj.reload(strObj);
        end
    end
end
