classdef LinePointList < robotics.ros.Message
    %LinePointList MATLAB implementation of msl_sensor_msgs/LinePointList
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_sensor_msgs/LinePointList' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8e923f31a929463488ca45a22d53e417' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MslMsgsPoint2dInfoClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_msgs/Point2dInfo') % Dispatch to MATLAB class for message type msl_msgs/Point2dInfo
    end
    
    properties (Dependent)
        ImageTime
        LinePoints
    end
    
    properties (Access = protected)
        Cache = struct('LinePoints', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ImageTime', 'LinePoints'} % List of non-constant message properties
        ROSPropertyList = {'imageTime', 'linePoints'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = LinePointList(msg)
            %LinePointList Construct the message object LinePointList
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function imagetime = get.ImageTime(obj)
            %get.ImageTime Get the value for property ImageTime
            imagetime = typecast(int64(obj.JavaMessage.getImageTime), 'uint64');
        end
        
        function set.ImageTime(obj, imagetime)
            %set.ImageTime Set the value for property ImageTime
            validateattributes(imagetime, {'numeric'}, {'nonempty', 'scalar'}, 'LinePointList', 'ImageTime');
            
            obj.JavaMessage.setImageTime(imagetime);
        end
        
        function linepoints = get.LinePoints(obj)
            %get.LinePoints Get the value for property LinePoints
            if isempty(obj.Cache.LinePoints)
                javaArray = obj.JavaMessage.getLinePoints;
                array = obj.readJavaArray(javaArray, obj.MslMsgsPoint2dInfoClass);
                obj.Cache.LinePoints = feval(obj.MslMsgsPoint2dInfoClass, array);
            end
            linepoints = obj.Cache.LinePoints;
        end
        
        function set.LinePoints(obj, linepoints)
            %set.LinePoints Set the value for property LinePoints
            if ~isvector(linepoints) && isempty(linepoints)
                % Allow empty [] input
                linepoints = feval([obj.MslMsgsPoint2dInfoClass '.empty'], 0, 1);
            end
            
            validateattributes(linepoints, {obj.MslMsgsPoint2dInfoClass}, {'vector'}, 'LinePointList', 'LinePoints');
            
            javaArray = obj.JavaMessage.getLinePoints;
            array = obj.writeJavaArray(linepoints, javaArray, obj.MslMsgsPoint2dInfoClass);
            obj.JavaMessage.setLinePoints(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.LinePoints)
                obj.Cache.LinePoints = [];
                obj.Cache.LinePoints = obj.LinePoints;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.LinePoints = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ImageTime = obj.ImageTime;
            
            % Recursively copy compound properties
            cpObj.LinePoints = copy(obj.LinePoints);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ImageTime = strObj.ImageTime;
            LinePointsCell = arrayfun(@(x) feval([obj.MslMsgsPoint2dInfoClass '.loadobj'], x), strObj.LinePoints, 'UniformOutput', false);
            obj.LinePoints = vertcat(LinePointsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ImageTime = obj.ImageTime;
            strObj.LinePoints = arrayfun(@(x) saveobj(x), obj.LinePoints);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_sensor_msgs.LinePointList.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_sensor_msgs.LinePointList;
            obj.reload(strObj);
        end
    end
end
