classdef SimulatorWorldModelData < robotics.ros.Message
    %SimulatorWorldModelData MATLAB implementation of msl_sensor_msgs/SimulatorWorldModelData
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_sensor_msgs/SimulatorWorldModelData' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '184a0bb258873f82d8c277fa8a2d09f3' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MslSensorMsgsWorldModelDataClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_sensor_msgs/WorldModelData') % Dispatch to MATLAB class for message type msl_sensor_msgs/WorldModelData
    end
    
    properties (Dependent)
        ReceiverID
        WorldModel
    end
    
    properties (Access = protected)
        Cache = struct('WorldModel', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ReceiverID', 'WorldModel'} % List of non-constant message properties
        ROSPropertyList = {'receiverID', 'worldModel'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SimulatorWorldModelData(msg)
            %SimulatorWorldModelData Construct the message object SimulatorWorldModelData
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function receiverid = get.ReceiverID(obj)
            %get.ReceiverID Get the value for property ReceiverID
            receiverid = int32(obj.JavaMessage.getReceiverID);
        end
        
        function set.ReceiverID(obj, receiverid)
            %set.ReceiverID Set the value for property ReceiverID
            validateattributes(receiverid, {'numeric'}, {'nonempty', 'scalar'}, 'SimulatorWorldModelData', 'ReceiverID');
            
            obj.JavaMessage.setReceiverID(receiverid);
        end
        
        function worldmodel = get.WorldModel(obj)
            %get.WorldModel Get the value for property WorldModel
            if isempty(obj.Cache.WorldModel)
                obj.Cache.WorldModel = feval(obj.MslSensorMsgsWorldModelDataClass, obj.JavaMessage.getWorldModel);
            end
            worldmodel = obj.Cache.WorldModel;
        end
        
        function set.WorldModel(obj, worldmodel)
            %set.WorldModel Set the value for property WorldModel
            validateattributes(worldmodel, {obj.MslSensorMsgsWorldModelDataClass}, {'nonempty', 'scalar'}, 'SimulatorWorldModelData', 'WorldModel');
            
            obj.JavaMessage.setWorldModel(worldmodel.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.WorldModel)
                obj.Cache.WorldModel.setJavaObject(worldmodel.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.WorldModel = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ReceiverID = obj.ReceiverID;
            
            % Recursively copy compound properties
            cpObj.WorldModel = copy(obj.WorldModel);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ReceiverID = strObj.ReceiverID;
            obj.WorldModel = feval([obj.MslSensorMsgsWorldModelDataClass '.loadobj'], strObj.WorldModel);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ReceiverID = obj.ReceiverID;
            strObj.WorldModel = saveobj(obj.WorldModel);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_sensor_msgs.SimulatorWorldModelData.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_sensor_msgs.SimulatorWorldModelData;
            obj.reload(strObj);
        end
    end
end
