classdef BallHandleCmd < robotics.ros.Message
    %BallHandleCmd MATLAB implementation of msl_actuator_msgs/BallHandleCmd
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_actuator_msgs/BallHandleCmd' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e69240c2dc380ac1fff9ca63c2b1baef' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        SenderID
        Enabled
        LeftMotor
        RightMotor
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Enabled', 'LeftMotor', 'RightMotor', 'SenderID'} % List of non-constant message properties
        ROSPropertyList = {'enabled', 'leftMotor', 'rightMotor', 'senderID'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = BallHandleCmd(msg)
            %BallHandleCmd Construct the message object BallHandleCmd
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function senderid = get.SenderID(obj)
            %get.SenderID Get the value for property SenderID
            senderid = int32(obj.JavaMessage.getSenderID);
        end
        
        function set.SenderID(obj, senderid)
            %set.SenderID Set the value for property SenderID
            validateattributes(senderid, {'numeric'}, {'nonempty', 'scalar'}, 'BallHandleCmd', 'SenderID');
            
            obj.JavaMessage.setSenderID(senderid);
        end
        
        function enabled = get.Enabled(obj)
            %get.Enabled Get the value for property Enabled
            enabled = logical(obj.JavaMessage.getEnabled);
        end
        
        function set.Enabled(obj, enabled)
            %set.Enabled Set the value for property Enabled
            validateattributes(enabled, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'BallHandleCmd', 'Enabled');
            
            obj.JavaMessage.setEnabled(enabled);
        end
        
        function leftmotor = get.LeftMotor(obj)
            %get.LeftMotor Get the value for property LeftMotor
            leftmotor = int32(obj.JavaMessage.getLeftMotor);
        end
        
        function set.LeftMotor(obj, leftmotor)
            %set.LeftMotor Set the value for property LeftMotor
            validateattributes(leftmotor, {'numeric'}, {'nonempty', 'scalar'}, 'BallHandleCmd', 'LeftMotor');
            
            obj.JavaMessage.setLeftMotor(leftmotor);
        end
        
        function rightmotor = get.RightMotor(obj)
            %get.RightMotor Get the value for property RightMotor
            rightmotor = int32(obj.JavaMessage.getRightMotor);
        end
        
        function set.RightMotor(obj, rightmotor)
            %set.RightMotor Set the value for property RightMotor
            validateattributes(rightmotor, {'numeric'}, {'nonempty', 'scalar'}, 'BallHandleCmd', 'RightMotor');
            
            obj.JavaMessage.setRightMotor(rightmotor);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SenderID = obj.SenderID;
            cpObj.Enabled = obj.Enabled;
            cpObj.LeftMotor = obj.LeftMotor;
            cpObj.RightMotor = obj.RightMotor;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SenderID = strObj.SenderID;
            obj.Enabled = strObj.Enabled;
            obj.LeftMotor = strObj.LeftMotor;
            obj.RightMotor = strObj.RightMotor;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SenderID = obj.SenderID;
            strObj.Enabled = obj.Enabled;
            strObj.LeftMotor = obj.LeftMotor;
            strObj.RightMotor = obj.RightMotor;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_actuator_msgs.BallHandleCmd.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_actuator_msgs.BallHandleCmd;
            obj.reload(strObj);
        end
    end
end
