classdef JoystickRobotIDs < robotics.ros.Message
    %JoystickRobotIDs MATLAB implementation of msl_actuator_msgs/JoystickRobotIDs
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_actuator_msgs/JoystickRobotIDs' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4f22efebf407aadba2ecc69df353d113' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Ids
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Ids'} % List of non-constant message properties
        ROSPropertyList = {'ids'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = JoystickRobotIDs(msg)
            %JoystickRobotIDs Construct the message object JoystickRobotIDs
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function ids = get.Ids(obj)
            %get.Ids Get the value for property Ids
            javaArray = obj.JavaMessage.getIds;
            array = obj.readJavaArray(javaArray, 'int32');
            ids = int32(array);
        end
        
        function set.Ids(obj, ids)
            %set.Ids Set the value for property Ids
            if ~isvector(ids) && isempty(ids)
                % Allow empty [] input
                ids = int32.empty(0,1);
            end
            
            validateattributes(ids, {'numeric'}, {'vector'}, 'JoystickRobotIDs', 'Ids');
            
            javaArray = obj.JavaMessage.getIds;
            array = obj.writeJavaArray(ids, javaArray, 'int32');
            obj.JavaMessage.setIds(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Ids = obj.Ids;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Ids = strObj.Ids;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Ids = obj.Ids;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_actuator_msgs.JoystickRobotIDs.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_actuator_msgs.JoystickRobotIDs;
            obj.reload(strObj);
        end
    end
end
