classdef MotionStatInfo < robotics.ros.Message
    %MotionStatInfo MATLAB implementation of msl_actuator_msgs/MotionStatInfo
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_actuator_msgs/MotionStatInfo' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '3d01848138c91542c07e61c489d11a2f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        SenderID
        SupplyVoltage
    end
    
    properties (Constant, Hidden)
        PropertyList = {'SenderID', 'SupplyVoltage'} % List of non-constant message properties
        ROSPropertyList = {'senderID', 'supplyVoltage'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MotionStatInfo(msg)
            %MotionStatInfo Construct the message object MotionStatInfo
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function senderid = get.SenderID(obj)
            %get.SenderID Get the value for property SenderID
            senderid = int32(obj.JavaMessage.getSenderID);
        end
        
        function set.SenderID(obj, senderid)
            %set.SenderID Set the value for property SenderID
            validateattributes(senderid, {'numeric'}, {'nonempty', 'scalar'}, 'MotionStatInfo', 'SenderID');
            
            obj.JavaMessage.setSenderID(senderid);
        end
        
        function supplyvoltage = get.SupplyVoltage(obj)
            %get.SupplyVoltage Get the value for property SupplyVoltage
            supplyvoltage = single(obj.JavaMessage.getSupplyVoltage);
        end
        
        function set.SupplyVoltage(obj, supplyvoltage)
            %set.SupplyVoltage Set the value for property SupplyVoltage
            validateattributes(supplyvoltage, {'numeric'}, {'nonempty', 'scalar'}, 'MotionStatInfo', 'SupplyVoltage');
            
            obj.JavaMessage.setSupplyVoltage(supplyvoltage);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.SenderID = obj.SenderID;
            cpObj.SupplyVoltage = obj.SupplyVoltage;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.SenderID = strObj.SenderID;
            obj.SupplyVoltage = strObj.SupplyVoltage;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.SenderID = obj.SenderID;
            strObj.SupplyVoltage = obj.SupplyVoltage;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_actuator_msgs.MotionStatInfo.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_actuator_msgs.MotionStatInfo;
            obj.reload(strObj);
        end
    end
end
