classdef VisionRelocTrigger < robotics.ros.Message
    %VisionRelocTrigger MATLAB implementation of msl_actuator_msgs/VisionRelocTrigger
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'msl_actuator_msgs/VisionRelocTrigger' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1343e9cfc80e509d361800792ddf2e6a' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MslMsgsPositionInfoClass = robotics.ros.msg.internal.MessageFactory.getClassForType('msl_msgs/PositionInfo') % Dispatch to MATLAB class for message type msl_msgs/PositionInfo
    end
    
    properties (Dependent)
        ReceiverID
        UsePose
        Position
    end
    
    properties (Access = protected)
        Cache = struct('Position', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Position', 'ReceiverID', 'UsePose'} % List of non-constant message properties
        ROSPropertyList = {'position', 'receiverID', 'usePose'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = VisionRelocTrigger(msg)
            %VisionRelocTrigger Construct the message object VisionRelocTrigger
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function receiverid = get.ReceiverID(obj)
            %get.ReceiverID Get the value for property ReceiverID
            receiverid = int32(obj.JavaMessage.getReceiverID);
        end
        
        function set.ReceiverID(obj, receiverid)
            %set.ReceiverID Set the value for property ReceiverID
            validateattributes(receiverid, {'numeric'}, {'nonempty', 'scalar'}, 'VisionRelocTrigger', 'ReceiverID');
            
            obj.JavaMessage.setReceiverID(receiverid);
        end
        
        function usepose = get.UsePose(obj)
            %get.UsePose Get the value for property UsePose
            usepose = logical(obj.JavaMessage.getUsePose);
        end
        
        function set.UsePose(obj, usepose)
            %set.UsePose Set the value for property UsePose
            validateattributes(usepose, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'VisionRelocTrigger', 'UsePose');
            
            obj.JavaMessage.setUsePose(usepose);
        end
        
        function position = get.Position(obj)
            %get.Position Get the value for property Position
            if isempty(obj.Cache.Position)
                obj.Cache.Position = feval(obj.MslMsgsPositionInfoClass, obj.JavaMessage.getPosition);
            end
            position = obj.Cache.Position;
        end
        
        function set.Position(obj, position)
            %set.Position Set the value for property Position
            validateattributes(position, {obj.MslMsgsPositionInfoClass}, {'nonempty', 'scalar'}, 'VisionRelocTrigger', 'Position');
            
            obj.JavaMessage.setPosition(position.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Position)
                obj.Cache.Position.setJavaObject(position.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Position = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ReceiverID = obj.ReceiverID;
            cpObj.UsePose = obj.UsePose;
            
            % Recursively copy compound properties
            cpObj.Position = copy(obj.Position);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ReceiverID = strObj.ReceiverID;
            obj.UsePose = strObj.UsePose;
            obj.Position = feval([obj.MslMsgsPositionInfoClass '.loadobj'], strObj.Position);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ReceiverID = obj.ReceiverID;
            strObj.UsePose = obj.UsePose;
            strObj.Position = saveobj(obj.Position);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.msl_actuator_msgs.VisionRelocTrigger.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.msl_actuator_msgs.VisionRelocTrigger;
            obj.reload(strObj);
        end
    end
end
