#pragma once

#include "DomainCondition.h"
#include <engine/BasicUtilityFunction.h>
#include <engine/DefaultUtilityFunction.h>
#include <engine/UtilityFunction.h>
/*PROTECTED REGION ID(incl1480766525772) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1480766525772) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1480766525772 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};
class RunTimeCondition1480766551805 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1480766547208 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
} /* namespace alica */
