#pragma once

#include "DomainCondition.h"
#include <engine/BasicUtilityFunction.h>
#include <engine/DefaultUtilityFunction.h>
#include <engine/UtilityFunction.h>
/*PROTECTED REGION ID(incl1468494583802) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1468494583802) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1468494583802 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};
class PreCondition1468919500674 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class RunTimeCondition1468495216221 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1468919192856 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
} /* namespace alica */
