#pragma once

#include "DomainCondition.h"
#include <engine/BasicUtilityFunction.h>
#include <engine/DefaultUtilityFunction.h>
#include <engine/UtilityFunction.h>
/*PROTECTED REGION ID(incl1519913821580) ENABLED START*/
// Add inlcudes here
/*PROTECTED REGION END*/
using namespace alica;

namespace alicaAutogenerated
{
/*PROTECTED REGION ID(meth1519913821580) ENABLED START*/
// Add other things here
/*PROTECTED REGION END*/
class UtilityFunction1519913821580 : public BasicUtilityFunction
{
    shared_ptr<UtilityFunction> getUtilityFunction(Plan *plan);
};
class RunTimeCondition1519914269940 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1519913901102 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1519914093807 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1519914333760 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1519913902356 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
class PreCondition1519914331734 : public DomainCondition
{
    bool evaluate(shared_ptr<RunningPlan> rp);
};
} /* namespace alica */
