#include "ServiceRobots/Charge1553186270535.h"
/*PROTECTED REGION ID(eph1553186270535) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Charge
/* generated comment
    Task: DefaultTask  -> EntryPoint-ID: 1553245568961
*/
shared_ptr<UtilityFunction> UtilityFunction1553186270535::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1553186270535) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553245704790, ConditionString: docked | fully charged (child success), Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Stop, (PlanID): 1553185137554
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1553245568961)
 *
 * States:
 *
 *   - SearchDock (1553245570484)
 *   - ChargeAccu (1553245570983)
 *   - FullyCharged (1553245572355)
 *
 * Vars:
 */
bool PreCondition1553245704790::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553245583942) ENABLED START*/
    if (this->fullyCharged() || this->isCharging()) {
        return true;
    }
    return false;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553245713697, ConditionString: accu full, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Stop, (PlanID): 1553185137554
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1553245568961)
 *
 * States:
 *
 *   - SearchDock (1553245570484)
 *   - ChargeAccu (1553245570983)
 *   - FullyCharged (1553245572355)
 *
 * Vars:
 */
bool PreCondition1553245713697::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553245593163) ENABLED START*/
    if (this->fullyCharged()) {
        return true;
    }
    return false;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
