#include "ServiceRobots/PickUp1553186320902.h"
/*PROTECTED REGION ID(eph1553186320902) ENABLED START*/
#include <TurtleBot.h>
#include <robot/SimulatedArm.h>

#include <ttb/TTBWorldModel.h>
#include <ttb/wm/TaskManager.h>
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:PickUp
// Check of RuntimeCondition - (Name): 1553251210748, (ConditionString): , (Comment) :

/*
 * Available Vars:
 *	- entity (1553251224214)
 */
bool RunTimeCondition1553251210748::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553251210748) ENABLED START*/
    return true;
    /*PROTECTED REGION END*/
}
/* generated comment
    Task: Fetch  -> EntryPoint-ID: 1553250907083
*/
shared_ptr<UtilityFunction> UtilityFunction1553186320902::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1553186320902) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553251380427, ConditionString: successfully picked up object, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): PickUp, (PlanID): 1553251475582
 *
 * Tasks:
 *
 *   - Fetch (1553250786927) (Entrypoint: 1553250907083)
 *
 * States:
 *
 *   - Grap (1553250909207)
 *   - DriveToPickUpPos (1553250909709)
 *   - PickUpFail (1553250911977)
 *   - DriveToObjectFail (1553250912679)
 *   - PickedUp (1553250914917)
 *
 * Vars:
 */
bool PreCondition1553251380427::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553251064992) ENABLED START*/
    auto currentTask = this->wm->taskManager.getNextTask();
    if (!currentTask || currentTask->getInformation().type != ttb_msgs::ServeTask::PICK_UP) {
        // current task is not for driving to an POI, so don't specify any problem descriptor
        return false;
    }
    auto objectName = ttb::TurtleBot::get(this->wm)->simulatedArm->getCarriedObjectName();
    if (objectName.compare(currentTask->getInformation().entity) != 0) {
        return false;
    } else {
        std::cout << "PickUp-Plan: Successfully picked up " << objectName << std::endl;
        this->wm->taskManager.popNextTask();
        return true;
    }
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553251368286, ConditionString: Failed to pick up object, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): PickUp, (PlanID): 1553251475582
 *
 * Tasks:
 *
 *   - Fetch (1553250786927) (Entrypoint: 1553250907083)
 *
 * States:
 *
 *   - Grap (1553250909207)
 *   - DriveToPickUpPos (1553250909709)
 *   - PickUpFail (1553250911977)
 *   - DriveToObjectFail (1553250912679)
 *   - PickedUp (1553250914917)
 *
 * Vars:
 */
bool PreCondition1553251368286::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553251068088) ENABLED START*/
    return rp->isAnyChildStatus(PlanStatus::Failed);
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553251329784, ConditionString: pos not reached, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): PickUp, (PlanID): 1553251475582
 *
 * Tasks:
 *
 *   - Fetch (1553250786927) (Entrypoint: 1553250907083)
 *
 * States:
 *
 *   - Grap (1553250909207)
 *   - DriveToPickUpPos (1553250909709)
 *   - PickUpFail (1553250911977)
 *   - DriveToObjectFail (1553250912679)
 *   - PickedUp (1553250914917)
 *
 * Vars:
 */
bool PreCondition1553251329784::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553251090038) ENABLED START*/
    // TODO still missing in beh
    return false;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553251355730, ConditionString: object position not available, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): DriveCloseToObject, (PlanID): 1553251534505
 *
 * Tasks:
 *
 *   - Fetch (1553250786927) (Entrypoint: 1553250907083)
 *
 * States:
 *
 *   - Grap (1553250909207)
 *   - DriveToPickUpPos (1553250909709)
 *   - PickUpFail (1553250911977)
 *   - DriveToObjectFail (1553250912679)
 *   - PickedUp (1553250914917)
 *
 * Vars:
 */
bool PreCondition1553251355730::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553251071386) ENABLED START*/
    // TODO missing in behaviour
    return false;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553251337135, ConditionString: arrived at poi, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): DriveCloseToObject, (PlanID): 1553251534505
 *
 * Tasks:
 *
 *   - Fetch (1553250786927) (Entrypoint: 1553250907083)
 *
 * States:
 *
 *   - Grap (1553250909207)
 *   - DriveToPickUpPos (1553250909709)
 *   - PickUpFail (1553250911977)
 *   - DriveToObjectFail (1553250912679)
 *   - PickedUp (1553250914917)
 *
 * Vars:
 */
bool PreCondition1553251337135::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553251083850) ENABLED START*/
    return rp->isAnyChildStatus(PlanStatus::Success);
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
