#include "ServiceRobots/Search1553186306469.h"
/*PROTECTED REGION ID(eph1553186306469) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Search
// Check of RuntimeCondition - (Name): 1553508629606, (ConditionString): , (Comment) :

/*
 * Available Vars:
 *	- entity (1553508638691)
 */
bool RunTimeCondition1553508629606::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553508629606) ENABLED START*/
    return true;
    /*PROTECTED REGION END*/
}
/* generated comment
    Task: Search  -> EntryPoint-ID: 1553508539549
*/
shared_ptr<UtilityFunction> UtilityFunction1553186306469::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1553186306469) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553508688960, ConditionString: entity found, Comment : MISSING_COMMENT
 *
 * Plans in State:
 *
 *   - Plan - (Name): Sweep, (PlanID): 1553508619994
 *
 * Tasks:
 *
 *   - Search (1553508529074) (Entrypoint: 1553508539549)
 *
 * States:
 *
 *   - DriveAround (1553508561976)
 *   - FoundEntity (1553508588008)
 *
 * Vars:
 */
bool PreCondition1553508688960::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553508681887) ENABLED START*/
    return false;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
