#include "ServiceRobots/ServeMaster1552995667134.h"
/*PROTECTED REGION ID(eph1552995667134) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:ServeMaster
/* generated comment
    Task: DefaultTask  -> EntryPoint-ID: 1552996396322
*/
shared_ptr<UtilityFunction> UtilityFunction1552995667134::getUtilityFunction(Plan* plan)
{
    /*PROTECTED REGION ID(1552995667134) ENABLED START*/
    std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
    return defaultFunction;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553086274283, ConditionString: , Comment :
 *
 * Plans in State:
 *
 *   - Plan - (Name): Stop, (PlanID): 1552996811900
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1552996396322)
 *
 * States:
 *
 *   - Stop (1552996403396)
 *   - Serve (1552996404209)
 *   - Charge (1552996405055)
 *
 * Vars:
 */
bool PreCondition1553086274283::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553086257494) ENABLED START*/
    return implement_me_1553086257494;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1552999434614, ConditionString: , Comment : FromServeToStop
 *
 * Plans in State:
 *
 *   - Plan - (Name): Serve, (PlanID): 1552996823626
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1552996396322)
 *
 * States:
 *
 *   - Stop (1552996403396)
 *   - Serve (1552996404209)
 *   - Charge (1552996405055)
 *
 * Vars:
 */
bool PreCondition1552999434614::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1552999417491) ENABLED START*/
    return implement_me_1552999417491;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1553086059295, ConditionString: , Comment :
 *
 * Plans in State:
 *
 *   - Plan - (Name): Serve, (PlanID): 1552996823626
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1552996396322)
 *
 * States:
 *
 *   - Stop (1552996403396)
 *   - Serve (1552996404209)
 *   - Charge (1552996405055)
 *
 * Vars:
 */
bool PreCondition1553086059295::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1553086051443) ENABLED START*/
    return implement_me_1553086051443;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1552997671153, ConditionString: , Comment : FromChargeToServe
 *
 * Plans in State:
 *
 *   - Plan - (Name): Charge, (PlanID): 1552996829354
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1552996396322)
 *
 * States:
 *
 *   - Stop (1552996403396)
 *   - Serve (1552996404209)
 *   - Charge (1552996405055)
 *
 * Vars:
 */
bool PreCondition1552997671153::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1552996768903) ENABLED START*/
    return implement_me_1552996768903;
    /*PROTECTED REGION END*/
}
/*
 *
 * Transition:
 *   - Name: 1552999379581, ConditionString: , Comment : FromChargeToStop
 *
 * Plans in State:
 *
 *   - Plan - (Name): Charge, (PlanID): 1552996829354
 *
 * Tasks:
 *
 *   - DefaultTask (1528875085489) (Entrypoint: 1552996396322)
 *
 * States:
 *
 *   - Stop (1552996403396)
 *   - Serve (1552996404209)
 *   - Charge (1552996405055)
 *
 * Vars:
 */
bool PreCondition1552999379581::evaluate(shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(1552999344041) ENABLED START*/
    return implement_me_1552999344041;
    /*PROTECTED REGION END*/
}
} // namespace alicaAutogenerated
