#include "Plans/Serve/Search1520437018620.h"
using namespace alica;
/*PROTECTED REGION ID(eph1520437018620) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:Search

    //Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) :  

    /* 
     * Available Vars:
     *	- entity (1520437454401)
     */
    bool RunTimeCondition1520437448508::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1520437448508) ENABLED START*/
        return true;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: Search  -> EntryPoint-ID: 1520437031578

     */
    shared_ptr<UtilityFunction> UtilityFunction1520437018620::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1520437018620) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: DriveAround in Plan: Search

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): SweepDefault, (PlanID): 1520437614544 
     *
     * Tasks: 
     *   - Search (1481544910904) (Entrypoint: 1520437031578)
     *
     * States:
     *   - DriveAround (1520437031577)
     *   - FoundEntity (1520438026668)
     *
     * Vars:
     */
    bool TransitionCondition1520438036937::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1520438035537) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: FoundEntity in Plan: Search

}
