#include "Plans/constraints/TurtleTestMaster1414681057676Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1414681057676) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TurtleTestMaster

/*		
 * Tasks: 
 * - EP:1414681057678 : DefaultTask (1414681164704)
 *
 * States:
 * - Stop (1414681057677)
 * - DoSomething (1414681069778)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: DoSomething

// State: DoSomething

}
