#include "Plans/Serve/PKVR16/SearchBoxes1481545038564.h"
using namespace alica;
/*PROTECTED REGION ID(eph1481545038564) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:SearchBoxes

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1481545053784

     */
    shared_ptr<UtilityFunction> UtilityFunction1481545038564::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1481545038564) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: SearchBoxes in Plan: SearchBoxes

}
