#include "Plans/Serve/PKVR16/SearchBoxes1481545038564.h"
using namespace alica;
/*PROTECTED REGION ID(eph1481545038564) ENABLED START*/ //Add additional using directives here
#include <memory>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:SearchBoxes

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1481545053784

     */
    shared_ptr<UtilityFunction> UtilityFunction1481545038564::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1481545038564) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: SearchBoxes in Plan: SearchBoxes

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : all landmarks found 
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveSearchPatternDefault, (PlanID): 1481546413105 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1481545053784)
     *
     * States:
     *   - SearchBoxes (1481545053783)
     *   - Investigate (1485789207566)
     *
     * Vars:
     */
    bool TransitionCondition1485789247329::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1485789245855) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: Investigate in Plan: SearchBoxes

}
