#include "ServiceRobots/constraints/Charge1553186270535Constraints.h"
/*PROTECTED REGION ID(ch1553186270535) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Charge
/*
 * Tasks:
 * - EP:1553245568961 : DefaultTask (1528875085489)
 *
 * States:
 * - SearchDock (1553245570484)
 * - ChargeAccu (1553245570983)
 * - FullyCharged (1553245572355)
 *
 * Vars:
 */

// State: SearchDock
// State: ChargeAccu
// State: FullyCharged
} // namespace alicaAutogenerated
