#include "ServiceRobots/constraints/Charge1552996829354Constraints.h"
/*PROTECTED REGION ID(ch1552996829354) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Charge
/*
 * Tasks:
 *
 * States:
 *
 * Vars:
 */

} // namespace alicaAutogenerated
