#include "ServiceRobots/constraints/DriveToPOI1553186299639Constraints.h"
/*PROTECTED REGION ID(ch1553186299639) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:DriveToPOI
/*
 * Tasks:
 * - EP:1553246730787 : DefaultTask (1528875085489)
 *
 * States:
 * - DriveToPOI (1553246732403)
 * - OpenDoor (1553246733927)
 * - AtGoalPOI (1553246736188)
 * - WasBlocked (1553246738057)
 *
 * Vars:
 * - door (1553249844851)
 * - poi (1553249850610)
 */
/*
 * RuntimeCondition - (Name): 1553249831272
 * (ConditionString):
 * Static Variables: poi door
 * Domain Variables:
 *
 */
void Constraint1553249831272::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1553249831272) ENABLED START*/
    // Please describe your runtime constraint here
    /*PROTECTED REGION END*/
}

// State: DriveToPOI
// State: OpenDoor
// State: AtGoalPOI
// State: WasBlocked
} // namespace alicaAutogenerated
