#include "ServiceRobots/constraints/PickUp1553186320902Constraints.h"
/*PROTECTED REGION ID(ch1553186320902) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:PickUp
/*
 * Tasks:
 * - EP:1553250907083 : Fetch (1553250786927)
 *
 * States:
 * - Grap (1553250909207)
 * - DriveToPickUpPos (1553250909709)
 * - PickUpFail (1553250911977)
 * - DriveToObjectFail (1553250912679)
 * - PickedUp (1553250914917)
 *
 * Vars:
 * - entity (1553251224214)
 */
/*
 * RuntimeCondition - (Name): 1553251210748
 * (ConditionString):
 * Static Variables: entity
 * Domain Variables:
 *
 */
void Constraint1553251210748::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1553251210748) ENABLED START*/
    // Please describe your runtime constraint here
    /*PROTECTED REGION END*/
}

// State: Grap
// State: DriveToPickUpPos
// State: PickUpFail
// State: DriveToObjectFail
// State: PickedUp
} // namespace alicaAutogenerated
