#include "ServiceRobots/constraints/PutDown1553186313956Constraints.h"
/*PROTECTED REGION ID(ch1553186313956) ENABLED START*/
#include <ttb/TTBWorldModel.h>
#include <ttb/wm/TaskManager.h>

#include <ttb_msgs/ServeTask.h>

#include <alica/reasoner/SimpleTerm.h>
#include <alica/reasoner/SimpleVariable.h>

#include <engine/constraintmodul/ProblemDescriptor.h>
#include <alica_solver_interface/SolverTerm.h>
#include <alica_solver_interface/SolverVariable.h>
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:PutDown
/*
 * Tasks:
 * - EP:1553251833164 : DefaultTask (1528875085489)
 *
 * States:
 * - DriveToPoint (1553251836208)
 * - PutDown (1553251837742)
 * - DriveToFailed (1553251860992)
 * - FailedToPlaceObject (1553251862908)
 * - ObjectPlaced (1553254969436)
 *
 * Vars:
 * - X (1553506228672)
 * - Y (1553506233885)
 * - Z (1553506237542)
 * - entity (1553506241307)
 */
/*
 * RuntimeCondition - (Name): 1553506204186
 * (ConditionString):
 * Static Variables: X Y Z entity
 * Domain Variables:
 *
 */
void Constraint1553506204186::getConstraint(std::shared_ptr<ProblemDescriptor> c, std::shared_ptr<RunningPlan> rp)
{
    /*PROTECTED REGION ID(cc1553506204186) ENABLED START*/
    auto wm = ttb::TTBWorldModel::get();
    auto currentTask = wm->taskManager.getNextTask();
    if (!currentTask || currentTask->getInformation().type != ttb_msgs::ServeTask::PUT_DOWN) {
        // current task is not for picking up an object, so don't specify any problem descriptor
        auto constraint = new alica::reasoner::SimpleTerm();
        for (auto var : c->getStaticVars()) {
            auto SimpleVar = reinterpret_cast<alica::reasoner::SimpleVariable*>(var);
            if (SimpleVar) {
                constraint->setVariable(SimpleVar, alica::reasoner::SimpleVariable::NO_VALUE);
            }
        }
        c->setConstraint(constraint);
        return;
    }

    auto constraint = new alica::reasoner::SimpleTerm();
    auto SimpleXVar = reinterpret_cast<alica::reasoner::SimpleVariable*>(c->getStaticVars().at(0));
    if (SimpleXVar) {
        auto x = currentTask->getInformation().entityPoint.x;
        constraint->setVariable(SimpleXVar, std::to_string(x));
    } else {
        std::cerr << "Constraint1520438401434: Variable type of X didn't fit!" << std::endl;
    }
    auto SimpleYVar = reinterpret_cast<alica::reasoner::SimpleVariable*>(c->getStaticVars().at(1));
    if (SimpleYVar) {
        auto y = currentTask->getInformation().entityPoint.y;
        constraint->setVariable(SimpleYVar, std::to_string(y));
    } else {
        std::cerr << "Constraint1520438401434: Variable type of Y didn't fit!" << std::endl;
    }
    auto SimpleZVar = reinterpret_cast<alica::reasoner::SimpleVariable*>(c->getStaticVars().at(2));
    if (SimpleZVar) {
        auto z = currentTask->getInformation().entityPoint.z;
        constraint->setVariable(SimpleZVar, std::to_string(z));
    } else {
        std::cerr << "Constraint1520438401434: Variable type of z didn't fit!" << std::endl;
    }
    auto SimpleEntityVar = reinterpret_cast<alica::reasoner::SimpleVariable*>(c->getStaticVars().at(3));
    if (SimpleEntityVar) {
        auto entity = currentTask->getInformation().entity;
        constraint->setVariable(SimpleEntityVar, entity);
    } else {
        std::cerr << "Constraint1520438401434: Variable type of Object Entity didn't fit!" << std::endl;
    }
    c->setConstraint(constraint);
    /*PROTECTED REGION END*/
}

// State: DriveToPoint
// State: PutDown
// State: DriveToFailed
// State: FailedToPlaceObject
// State: ObjectPlaced
} // namespace alicaAutogenerated
