#include "ServiceRobots/constraints/Serve1552996823626Constraints.h"
/*PROTECTED REGION ID(ch1552996823626) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:Serve
/*
 * Tasks:
 * - EP:1552996861087 : DefaultTask (1528875085489)
 *
 * States:
 * - WaitForTask (1552996863380)
 * - DriveTo (1552997081975)
 * - PickUp (1552997082976)
 * - SearchFor (1552997084306)
 *
 * Vars:
 */

// State: WaitForTask
// State: DriveTo
// State: PickUp
// State: SearchFor
} // namespace alicaAutogenerated
