#include "ConditionCreator.h"

#include  "Plans/TurtleGenericTestMaster1414681057676.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1414681086048:

                return make_shared<TransitionCondition1414681086048>();

                break;

            case 1414681505635:

                return make_shared<TransitionCondition1414681505635>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
