#include "ConditionCreator.h"

#include  "Plans/TestPOI1454329810785.h"

#include  "Plans/ChargeAndSimpleDriveTest1414681057676.h"

#include  "Plans/TurtleGenericTestMaster1454329729827.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1454329835328:

                return make_shared<TransitionCondition1454329835328>();

                break;

            case 1454329836408:

                return make_shared<TransitionCondition1454329836408>();

                break;

            case 1414681505635:

                return make_shared<TransitionCondition1414681505635>();

                break;

            case 1447068020434:

                return make_shared<TransitionCondition1447068020434>();

                break;

            case 1447068022583:

                return make_shared<TransitionCondition1447068022583>();

                break;

            case 1447068025867:

                return make_shared<TransitionCondition1447068025867>();

                break;

            case 1447068027882:

                return make_shared<TransitionCondition1447068027882>();

                break;

            case 1447919930987:

                return make_shared<TransitionCondition1447919930987>();

                break;

            case 1447958162066:

                return make_shared<TransitionCondition1447958162066>();

                break;

            case 1447958165046:

                return make_shared<TransitionCondition1447958165046>();

                break;

            case 1447958174005:

                return make_shared<TransitionCondition1447958174005>();

                break;

            case 1454329746996:

                return make_shared<TransitionCondition1454329746996>();

                break;

            case 1454329748126:

                return make_shared<TransitionCondition1454329748126>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
