#include "ConstraintCreator.h"

#include "ServiceRobots/constraints/Charge1552996829354Constraints.h"
#include "ServiceRobots/constraints/Serve1552996823626Constraints.h"
#include "ServiceRobots/constraints/ServeMaster1552995667134Constraints.h"

#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

ConstraintCreator::ConstraintCreator() {}

ConstraintCreator::~ConstraintCreator() {}

shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
{
    switch (constraintConfId) {
    default:
        std::cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << std::endl;
        throw new std::exception();
        break;
    }
}

} // namespace alica
