#include "ConstraintCreator.h"
#include <iostream>

#include  "Plans/Tests/constraints/TurtleGenericTestMaster1454329729827Constraints.h"

#include  "Plans/Serve/constraints/Charge1454331030770Constraints.h"

#include  "Plans/Serve/constraints/ServeMaster1454332108133Constraints.h"

#include  "Plans/Serve/constraints/Serve1454331313621Constraints.h"

#include  "Plans/Tests/constraints/TestPOI1454329810785Constraints.h"

using namespace std;
using namespace alicaAutogenerated;

namespace alica
{

    ConstraintCreator::ConstraintCreator()
    {
    }

    ConstraintCreator::~ConstraintCreator()
    {
    }

    shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
    {
        switch (constraintConfId)
        {

            default:
                cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << endl;
                throw new exception();
                break;
        }
    }

}
