#include <iostream>
#include "UtilityFunctionCreator.h"

#include  "Plans/Tests/TurtleGenericTestMaster1454329729827.h"

#include  "Plans/Serve/Charge1454331030770.h"

#include  "Plans/Serve/ServeMaster1454332108133.h"

#include  "Plans/Tests/ChargeAndSimpleDriveTest1414681057676.h"

#include  "Plans/Serve/Serve1454331313621.h"

#include  "Plans/Tests/TestPOI1454329810785.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }

    shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
    {
        switch (utilityfunctionConfId)
        {

            case 1454329729827:
                return make_shared<UtilityFunction1454329729827>();
                break;

            case 1454331030770:
                return make_shared<UtilityFunction1454331030770>();
                break;

            case 1454332108133:
                return make_shared<UtilityFunction1454332108133>();
                break;

            case 1414681057676:
                return make_shared<UtilityFunction1414681057676>();
                break;

            case 1454331313621:
                return make_shared<UtilityFunction1454331313621>();
                break;

            case 1454329810785:
                return make_shared<UtilityFunction1454329810785>();
                break;

            default:
                cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
                throw new exception();
                break;
        }
    }

}
