#include "UtilityFunctionCreator.h"
#include "ServiceRobots/Charge1552996829354.h"
#include "ServiceRobots/Serve1552996823626.h"
#include "ServiceRobots/ServeMaster1552995667134.h"
#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

UtilityFunctionCreator::~UtilityFunctionCreator() {}

UtilityFunctionCreator::UtilityFunctionCreator() {}

std::shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
{
    switch (utilityfunctionConfId) {
    case 1552995667134:
        return std::make_shared<UtilityFunction1552995667134>();
        break;
    case 1552996823626:
        return std::make_shared<UtilityFunction1552996823626>();
        break;
    case 1552996829354:
        return std::make_shared<UtilityFunction1552996829354>();
        break;
    default:
        std::cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << std::endl;
        throw new std::exception();
        break;
    }
}

} // namespace alica
