#include "TestPlans4Parsing/constraints/ParsingTestMaster1554234501483Constraints.h"
/*PROTECTED REGION ID(ch1554234501483) ENABLED START*/
// Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
// Plan:ParsingTestMaster
/*
 * Tasks:
 * - EP:1554234527864 : DefaultTask (1528875085489)
 *
 * States:
 * - Default Name (1554234522334)
 *
 * Vars:
 * - Var1 (1554234508051)
 * - Var2 (1554234511544)
 * - Var3 (1554234514877)
 */

// State: Default Name
} // namespace alicaAutogenerated
