#include "Plans/constraints/TurtleGenericTestMaster1414681057676Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1414681057676) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TurtleGenericTestMaster

/*		
 * Tasks: 
 * - EP:1414681057678 : DefaultTask (1414681164704)
 *
 * States:
 * - Stop (1414681057677)
 * - DriveForward (1414681069778)
 * - Rotating (1447067994402)
 * - SearchDockingStation (1447919813367)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: DriveForward

// State: DriveForward

// State: Rotating

// State: Rotating

// State: SearchDockingStation

// State: SearchDockingStation

}
