#include "Plans/Wumpus/constraints/WumpusMaster1489673406228Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1489673406228) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:WumpusMaster

/*		
 * Tasks: 
 * - EP:1489673406230 : DefaultTask (1414681164704)
 *
 * States:
 * - Stop (1489673406229)
 * - Play (1489673551929)
 * - AgentDead (1489673616222)
 * - AgentLeftCave (1489673668786)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: Play

// State: Play

// State: AgentDead

// State: AgentDead

// State: AgentLeftCave

// State: AgentLeftCave

}
